graphhopper:
  datareader.file: ../openrouteservice/openrouteservice-api-tests/data/heidelberg.osm.gz
  gtfs.file: ../openrouteservice/openrouteservice-api-tests/data/vrn_gtfs.zip
  graph.location: graphs/hdvrn

  profiles:
    - name: foot
      vehicle: foot
      weighting: fastest

server:
  application_connectors:
    - type: http
      port: 8989
      bind_host: localhost
  admin_connectors:
    - type: http
      port: 8990
      bind_host: localhost
