# This workflow will build a package using Maven and then publish it to repo.heigit.org when a release is created

name: Publish on repo.heigit.org

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Set version
      run: mvn versions:set -DnewVersion=${{ github.ref_name }}

    - name: Build with Maven
      run: mvn -B install -Dmaven.test.skip=true -f pom.xml

    - name: Prepare generated files
      run: 'mkdir -p dist/com/github/GIScience/graphhopper &&
      cp -R ~/.m2/repository/com/github/GIScience/graphhopper/* ./dist/com/github/GIScience/graphhopper &&
      find dist -type f -name "*.xml" -delete && find dist -type f -name "*.repositories" -delete'

    - name: List files
      run: pwd && ls -laR dist/*

    - name: Publish to repository
      uses: advancedcsg-open/action-jfrog-cli@master
      with:
        url: 'https://repo.heigit.org/'
        credentials type: 'accesstoken'
        access token: ${{ secrets.ARTIFACTORY_ACCESSTOKEN }}
        args: u "dist/" "libs-release-local/" --recursive=true
