# This workflow will build a package using Maven and then publish it to repo.heigit.org when a release is created

name: Publish on repo.heigit.org

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: List generated files
      run: ls -la dist/

#    - name: publish to artifactory
#      uses: advancedcsg-open/action-jfrog-cli@master
#      with:
#        url: 'https://repo.heigit.org/'
#        credentials type: 'apikey'
#        apikey: ${{ secrets.ARTIFACTORY_ACCESSTOKEN }}
#        args: u "dist/*" "libs-release-local/" --recursive=true --build-name=graphhopper
        
#    - name: Publish to GitHub Packages Apache Maven
#      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
#      env:
#        GITHUB_TOKEN: ${{ github.token }}
